// demos/vue-demo/src/App.vue
<template>
  <div id="app">
    <h1>🎮 Gamify Vue Demo</h1>
    <p>Experience the power of gamification with Vue.js!</p>
    
    <div class="gamify-container">
      <!-- User Panel -->
      <div class="user-panel">
        <h2>👤 User Profile</h2>
        <div v-if="user">
          <h3>{{ user.name || 'Anonymous Player' }}</h3>
          
          <div class="stats-grid">
            <div class="stat-card">
              <div class="stat-value">{{ user.level }}</div>
              <div class="stat-label">Level</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{ user.xp }}</div>
              <div class="stat-label">XP</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{ user.badges.length }}</div>
              <div class="stat-label">Badges</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{ user.achievements.length }}</div>
              <div class="stat-label">Achievements</div>
            </div>
          </div>
          
          <div>
            <strong>Progress to Level {{ user.level + 1 }}</strong>
            <div class="progress-bar">
              <div 
                class="progress-fill" 
                :style="{ width: `${levelProgress.progress * 100}%` }"
              ></div>
            </div>
            <small>{{ levelProgress.current }} / {{ levelProgress.next }} XP</small>
          </div>
          
          <div v-if="user.badges.length > 0">
            <h4>🏆 Recent Badges</h4>
            <div class="achievements-list">
              <div 
                v-for="badge in user.badges.slice(-3)" 
                :key="badge.id"
                class="achievement-card"
              >
                <div class="achievement-title">{{ badge.name }}</div>
                <div class="achievement-desc">{{ badge.description }}</div>
              </div>
            </div>
          </div>
        </div>
        <div v-else>
          <p>Loading user data...</p>
        </div>
      </div>
      
      <!-- Actions Panel -->
      <div class="actions-panel">
        <h2>🎯 Actions</h2>
        <p>Click buttons to earn XP and progress!</p>
        
        <div>
          <button 
            class="action-button" 
            @click="performAction('click', 10)"
          >
            🖱️ Click (10 XP)
          </button>
          
          <button 
            class="action-button" 
            @click="performAction('scroll', 5)"
          >
            📜 Scroll (5 XP)
          </button>
          
          <button 
            class="action-button" 
            @click="performAction('share', 25)"
          >
            📤 Share (25 XP)
          </button>
          
          <button 
            class="action-button" 
            @click="performAction('comment', 15)"
          >
            💬 Comment (15 XP)
          </button>
          
          <button 
            class="action-button" 
            @click="performAction('like', 8)"
          >
            ❤️ Like (8 XP)
          </button>
          
          <button 
            class="action-button" 
            @click="performAction('complete_task', 50)"
          >
            ✅ Complete Task (50 XP)
          </button>
        </div>
        
        <div style="margin-top: 2rem;">
          <h3>📊 Analytics</h3>
          <div class="stats-grid">
            <div class="stat-card">
              <div class="stat-value">{{ engagementScore }}</div>
              <div class="stat-label">Engagement Score</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">{{ totalActions }}</div>
              <div class="stat-label">Total Actions</div>
            </div>
          </div>
        </div>
        
        <div style="margin-top: 2rem;">
          <h3>🏆 Achievements</h3>
          <div v-if="achievements.length > 0" class="achievements-list">
            <div 
              v-for="achievement in achievements" 
              :key="achievement.id"
              class="achievement-card"
            >
              <div class="achievement-title">{{ achievement.title }}</div>
              <div class="achievement-desc">{{ achievement.description }}</div>
            </div>
          </div>
          <p v-else>No achievements earned yet. Keep playing!</p>
        </div>
      </div>
    </div>
    
    <!-- Notifications -->
    <div v-if="notification" class="notification">
      {{ notification }}
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { GamifyEngine } from '@gamify-ui/core'

// Initialize the gamification engine
const engine = new GamifyEngine({
  debug: true,
  theme: {
    colors: {
      primary: '#646cff',
      secondary: '#535bf2',
      success: '#10b981',
      warning: '#f59e0b',
      error: '#ef4444'
    }
  }
})

// Reactive state
const user = ref<any>(null)
const levelProgress = ref({ current: 0, next: 100, progress: 0 })
const achievements = ref<any[]>([])
const engagementScore = ref(0)
const totalActions = ref(0)
const notification = ref('')

// Create user on mount
onMounted(() => {
  const userId = 'vue-demo-user'
  user.value = engine.createUser(userId, 'Vue Player', 'vue@example.com')
  
  // Start analytics session
  engine.startSession(userId)
  
  // Set up event listeners
  engine.onLevelUp().subscribe((updatedUser) => {
    if (updatedUser.id === userId) {
      showNotification(`🎉 Level Up! You're now level ${updatedUser.level}!`)
      updateUserData()
    }
  })
  
  engine.onAchievement().subscribe((data) => {
    if (data.user.id === userId) {
      showNotification(`🏆 Achievement Unlocked: ${data.achievement.title}!`)
      updateUserData()
    }
  })
  
  // Initial data update
  updateUserData()
})

// Computed properties
const updateUserData = () => {
  if (user.value) {
    levelProgress.value = engine.getLevelProgress(user.value)
    achievements.value = engine.getUserAchievements(user.value.id)
    engagementScore.value = engine.getEngagementScore(user.value.id)
    
    // Get user metrics for total actions
    const metrics = engine.getUserMetrics(user.value.id)
    totalActions.value = metrics?.totalXp || 0
  }
}

// Actions
const performAction = (actionType: string, xp: number) => {
  if (!user.value) return
  
  engine.triggerEvent(user.value.id, actionType, { xp })
  showNotification(`+${xp} XP for ${actionType}!`)
  updateUserData()
}

const showNotification = (message: string) => {
  notification.value = message
  setTimeout(() => {
    notification.value = ''
  }, 3000)
}
</script>

// demo/react-demo/src/App.tsx
import React, { useState, useEffect } from 'react';
import { GamifyEngine, GamifyProvider, useGamify, useLevelUp, useAchievement, useLeaderboard } from '@gamify-ui/core';
import './App.css';

// User Profile Component
const UserProfile: React.FC<{ userId: string }> = ({ userId }) => {
  const { user, loading, error, triggerEvent, level, xp, progress } = useGamify(userId);
  const levelUp = useLevelUp(userId);
  const achievement = useAchievement(userId);

  const [notification, setNotification] = useState<string | null>(null);

  useEffect(() => {
    if (levelUp) {
      setNotification(`🎉 Level Up! You're now level ${levelUp.level}!`);
      setTimeout(() => setNotification(null), 3000);
    }
  }, [levelUp]);

  useEffect(() => {
    if (achievement) {
      setNotification(`🏆 Achievement Unlocked: ${achievement.achievement.title}!`);
      setTimeout(() => setNotification(null), 3000);
    }
  }, [achievement]);

  if (loading) return <div className="loading">Loading...</div>;
  if (error) return <div className="error">Error: {error.message}</div>;
  if (!user) return <div className="error">No user found</div>;

  const actions = [
    { name: 'Click', type: 'click', icon: '🖱️' },
    { name: 'Scroll', type: 'scroll', icon: '📜' },
    { name: 'Share', type: 'share', icon: '📤' },
    { name: 'Comment', type: 'comment', icon: '💬' },
    { name: 'Daily Check-in', type: 'daily', icon: '📅' },
    { name: 'Weekly Goal', type: 'weekly', icon: '📊' }
  ];

  return (
    <div className="user-panel">
      {notification && (
        <div className="notification">
          {notification}
        </div>
      )}
      
      <h2>👤 User Profile</h2>
      
      <div className="user-info">
        <h3>Player Stats</h3>
        <div className="stat-grid">
          <div className="stat-item">
            <div className="stat-value">{level}</div>
            <div className="stat-label">Level</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">{xp}</div>
            <div className="stat-label">XP</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">{user.badges.length}</div>
            <div className="stat-label">Badges</div>
          </div>
          <div className="stat-item">
            <div className="stat-value">{user.streaks.length}</div>
            <div className="stat-label">Streaks</div>
          </div>
        </div>
        
        <div className="progress-bar">
          <div 
            className="progress-fill" 
            style={{ width: `${progress * 100}%` }}
          />
        </div>
        <div className="progress-text">
          {Math.round(progress * 100)}% to next level
        </div>
      </div>

      <div className="user-info">
        <h3>🎯 Actions</h3>
        <div className="actions">
          {actions.map(action => (
            <button
              key={action.type}
              className="btn btn-primary"
              onClick={() => triggerEvent(action.type, { element: 'button' })}
            >
              {action.icon} {action.name}
            </button>
          ))}
        </div>
      </div>
    </div>
  );
};

// Leaderboard Component
const Leaderboard: React.FC = () => {
  const leaderboard = useLeaderboard(10);

  return (
    <div className="leaderboard-panel">
      <h2>🏆 Leaderboard</h2>
      <div className="leaderboard">
        {leaderboard.map((entry, index) => (
          <div key={entry.userId} className="leaderboard-item">
            <div className={`rank ${index < 3 ? `rank-${index + 1}` : 'rank-other'}`}>
              {entry.rank}
            </div>
            <div className="user-details">
              <div className="user-name">{entry.userName}</div>
              <div className="user-stats">Level {entry.level} • {entry.score} XP</div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

// Main App Component
const App: React.FC = () => {
  const [engine] = useState(() => {
    const gamifyEngine = new GamifyEngine({
      debug: true,
      theme: {
        colors: {
          primary: '#667eea',
          secondary: '#764ba2',
          success: '#28a745',
          warning: '#ffc107',
          error: '#dc3545',
          background: '#ffffff',
          surface: '#f8f9fa',
          text: '#495057'
        }
      }
    });

    // Create demo users
    const users = [
      { id: 'user-1', name: 'John Doe', xp: 0 },
      { id: 'user-2', name: 'Jane Smith', xp: 150 },
      { id: 'user-3', name: 'Bob Johnson', xp: 300 },
      { id: 'user-4', name: 'Alice Brown', xp: 500 },
      { id: 'user-5', name: 'Charlie Wilson', xp: 750 }
    ];

    users.forEach(user => {
      gamifyEngine.createUser(user.id, user.name);
      if (user.xp > 0) {
        gamifyEngine.updateUser(user.id, { xp: user.xp });
      }
    });

    // Add game rules
    gamifyEngine.addRule({
      id: 'click-rule',
      trigger: {
        type: 'click',
        reward: { xp: 10 }
      },
      enabled: true,
      priority: 1
    });

    gamifyEngine.addRule({
      id: 'scroll-rule',
      trigger: {
        type: 'scroll',
        reward: { xp: 5 }
      },
      enabled: true,
      priority: 1
    });

    gamifyEngine.addRule({
      id: 'share-rule',
      trigger: {
        type: 'share',
        reward: { xp: 25 }
      },
      enabled: true,
      priority: 1
    });

    gamifyEngine.addRule({
      id: 'comment-rule',
      trigger: {
        type: 'comment',
        reward: { xp: 15 }
      },
      enabled: true,
      priority: 1
    });

    gamifyEngine.addRule({
      id: 'daily-rule',
      trigger: {
        type: 'daily',
        reward: { xp: 50 }
      },
      enabled: true,
      priority: 1
    });

    gamifyEngine.addRule({
      id: 'weekly-rule',
      trigger: {
        type: 'weekly',
        reward: { xp: 100 }
      },
      enabled: true,
      priority: 1
    });

    // Add missions
    gamifyEngine.addMission({
      id: 'first-click',
      title: 'First Click',
      description: 'Click for the first time',
      goal: { type: 'event', value: 1 },
      reward: { xp: 50 },
      repeatable: false,
      difficulty: 'easy'
    });

    gamifyEngine.addMission({
      id: 'click-master',
      title: 'Click Master',
      description: 'Click 10 times',
      goal: { type: 'event', value: 10 },
      reward: { xp: 100 },
      repeatable: false,
      difficulty: 'medium'
    });

    return gamifyEngine;
  });

  return (
    <GamifyProvider engine={engine}>
      <div className="container">
        <div className="header">
          <h1>🎮 @gamify-ui/core</h1>
          <p>React Gamification Demo</p>
        </div>

        <div className="content">
          <UserProfile userId="user-1" />
          <Leaderboard />
        </div>
      </div>
    </GamifyProvider>
  );
};

export default App;
